version: '3'

services:
  nestjs-producer:
    container_name: nestjs-producer
    build:
      context: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
      # - 9229:9229
    command: npm run start:dev
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - backend

networks:
  backend:
