version: '3'

services:
  nestjs-consumer:
    container_name: nestjs-consumer
    build:
      context: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3001:3001
      - 9229:9229
    command: npm run start:dev
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - backend

networks:
  backend:
